import { ReportedAdjudicationDto } from '../../@types/adjudicationsApiTypes'
import { IncentiveReviewSummary } from '../../@types/incentivesApiTypes'
import { TimetableEvents } from '../../@types/launchpad'

/* eslint-disable import/prefer-default-export */
export const events: TimetableEvents = {
  '2024-01-11': {
    morning: {
      finished: false,
      events: [
        {
          description: 'AM 1 HIGHER FUNC. SKILLS',
          startTime: '8.50am',
          endTime: '10.20am',
          location: 'Level2 class6',
          timeString: '8.50am to 10.20am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'AM 2 HIGHER FUNC. SKILLS',
          startTime: '10.20am',
          endTime: '11.50am',
          location: 'Level2 class6',
          timeString: '10.20am to 11.50am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    afternoon: {
      finished: false,
      events: [
        {
          description: 'PM 3 HIGHER FUNC. SKILLS',
          startTime: '1.40pm',
          endTime: '3.10pm',
          location: 'Level2 class6',
          timeString: '1.40pm to 3.10pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'PM 4 HIGHER FUNC. SKILLS',
          startTime: '3.10pm',
          endTime: '4.40pm',
          location: 'Level2 class6',
          timeString: '3.10pm to 4.40pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    evening: {
      finished: false,
      events: [
        {
          description: 'ED CLEANING ORD.',
          startTime: '6.00pm',
          endTime: '7.00pm',
          location: 'Wing cleaner',
          timeString: '6.00pm to 7.00pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    title: 'Today',
  },
  '2024-01-12': {
    morning: {
      finished: false,
      events: [
        {
          description: 'AM 1 GYM',
          startTime: '8.50am',
          endTime: '10.20am',
          location: 'Gym domestics',
          timeString: '8.50am to 10.20am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'AM 2 GYM',
          startTime: '10.20am',
          endTime: '11.50am',
          location: 'Gym domestics',
          timeString: '10.20am to 11.50am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    afternoon: {
      finished: false,
      events: [
        {
          description: 'PM 3 HIGHER FUNC. SKILLS',
          startTime: '1.40pm',
          endTime: '3.10pm',
          location: 'Level2 class6',
          timeString: '1.40pm to 3.10pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'PM 4 HIGHER FUNC. SKILLS',
          startTime: '3.10pm',
          endTime: '4.40pm',
          location: 'Level2 class6',
          timeString: '3.10pm to 4.40pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    evening: {
      finished: false,
      events: [
        {
          description: 'ED CLEANING ORD.',
          startTime: '6.00pm',
          endTime: '7.00pm',
          location: 'Wing cleaner',
          timeString: '6.00pm to 7.00pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    title: 'Tomorrow',
  },
  '2024-01-13': {
    morning: {
      finished: false,
      events: [],
    },
    afternoon: {
      finished: false,
      events: [],
    },
    evening: {
      finished: false,
      events: [],
    },
    title: 'Saturday 13 January',
  },
  '2024-01-14': {
    morning: {
      finished: false,
      events: [],
    },
    afternoon: {
      finished: false,
      events: [],
    },
    evening: {
      finished: false,
      events: [],
    },
    title: 'Sunday 14 January',
  },
  '2024-01-15': {
    morning: {
      finished: false,
      events: [
        {
          description: 'AM 1 HIGHER FUNC. SKILLS',
          startTime: '8.50am',
          endTime: '10.20am',
          location: 'Level2 class6',
          timeString: '8.50am to 10.20am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'AM 2 HIGHER FUNC. SKILLS',
          startTime: '10.20am',
          endTime: '11.50am',
          location: 'Level2 class6',
          timeString: '10.20am to 11.50am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    afternoon: {
      finished: false,
      events: [
        {
          description: 'PM 3 HIGHER FUNC. SKILLS',
          startTime: '1.40pm',
          endTime: '3.10pm',
          location: 'Level2 class6',
          timeString: '1.40pm to 3.10pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'PM 4 HIGHER FUNC. SKILLS',
          startTime: '3.10pm',
          endTime: '4.40pm',
          location: 'Level2 class6',
          timeString: '3.10pm to 4.40pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    evening: {
      finished: false,
      events: [
        {
          description: 'ED CLEANING ORD.',
          startTime: '6.00pm',
          endTime: '7.00pm',
          location: 'Wing cleaner',
          timeString: '6.00pm to 7.00pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    title: 'Monday 15 January',
  },
  '2024-01-16': {
    morning: {
      finished: false,
      events: [
        {
          description: 'AM 1 HIGHER FUNC. SKILLS',
          startTime: '8.50am',
          endTime: '10.20am',
          location: 'Level2 class6',
          timeString: '8.50am to 10.20am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'AM 2 HIGHER FUNC. SKILLS',
          startTime: '10.20am',
          endTime: '11.50am',
          location: 'Level2 class6',
          timeString: '10.20am to 11.50am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    afternoon: {
      finished: false,
      events: [
        {
          description: 'PM 3 HIGHER FUNC. SKILLS',
          startTime: '1.40pm',
          endTime: '3.10pm',
          location: 'Level2 class6',
          timeString: '1.40pm to 3.10pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'PM 4 HIGHER FUNC. SKILLS',
          startTime: '3.10pm',
          endTime: '4.40pm',
          location: 'Level2 class6',
          timeString: '3.10pm to 4.40pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    evening: {
      finished: false,
      events: [
        {
          description: 'ED CLEANING ORD.',
          startTime: '6.00pm',
          endTime: '7.00pm',
          location: 'Wing cleaner',
          timeString: '6.00pm to 7.00pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    title: 'Tuesday 16 January',
  },
  '2024-01-17': {
    morning: {
      finished: false,
      events: [
        {
          description: 'AM 1 HIGHER FUNC. SKILLS',
          startTime: '8.50am',
          endTime: '10.20am',
          location: 'Level2 class6',
          timeString: '8.50am to 10.20am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'AM 2 HIGHER FUNC. SKILLS',
          startTime: '10.20am',
          endTime: '11.50am',
          location: 'Level2 class6',
          timeString: '10.20am to 11.50am',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    afternoon: {
      finished: false,
      events: [
        {
          description: 'PM 3 HIGHER FUNC. SKILLS',
          startTime: '1.40pm',
          endTime: '3.10pm',
          location: 'Level2 class6',
          timeString: '1.40pm to 3.10pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
        {
          description: 'PM 4 HIGHER FUNC. SKILLS',
          startTime: '3.10pm',
          endTime: '4.40pm',
          location: 'Level2 class6',
          timeString: '3.10pm to 4.40pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    evening: {
      finished: false,
      events: [
        {
          description: 'ED CLEANING ORD.',
          startTime: '6.00pm',
          endTime: '7.00pm',
          location: 'Wing cleaner',
          timeString: '6.00pm to 7.00pm',
          eventType: 'PRISON_ACT',
          finished: false,
          status: 'SCH',
          paid: false,
        },
      ],
    },
    title: 'Wednesday 17 January',
  },
}

export const incentives: IncentiveReviewSummary = {
  id: 2761962,
  iepCode: 'STD',
  iepLevel: 'Standard',
  prisonerNumber: 'X1234XX',
  bookingId: 123456,
  iepDate: '2017-01-09',
  iepTime: '2017-01-09T10:25:30',
  iepDetails: [],
  nextReviewDate: '2018-01-09',
  daysSinceReview: 2572,
}

export const reportedAdjudication: ReportedAdjudicationDto = {
  chargeNumber: '409064-1',
  prisonerNumber: 'G6046GQ',
  gender: 'MALE',
  incidentDetails: {
    locationId: 78668,
    dateTimeOfIncident: '2011-01-28T11:52:00',
    dateTimeOfDiscovery: '2011-01-28T11:52:00',
    handoverDeadline: '2011-01-30T11:52:00',
  },
  isYouthOffender: false,
  incidentRole: {},
  offenceDetails: {
    offenceCode: 0,
    offenceRule: {
      paragraphNumber: '51:12',
      paragraphDescription:
        'Has in his possession-(a) any unauthorised article, or (b) a greater quantity of any article than he is authorised to have',
    },
  },
  incidentStatement: {
    statement:
      'rjowXkIlphbUTbkxkvuJBsgqXYnbsywoUbmLQPdVuYectcgbJrkhoGlOIcYPjEZJJNgjrOTfUYmvUNSgQYIhEiCcEKazUCeEmKMlqzHdQXcJTEvYBgwonclNYGjLRxjGiygLMZKhwrjowXkIlphbUTbkxkvuJBsgqXYnbsywoUbmLQPdVuYectcgbJrkhoGlOIcYPjEZJJNgjrOTfUYmvUNSgQYIhEiCcEKazUCeEmKMlqzHdQXcJTEvYBgwonclNYGjLRxjGiygLMZKhw',
    completed: true,
  },
  createdByUserId: 'HQT52N',
  createdDateTime: '2011-01-28T11:52:00',
  status: 'NOT_PROCEED',
  damages: [
    {
      code: 'FURNITURE_OR_FABRIC_REPAIR',
      details: 'fZBeRelBeoedfZBeRelBeoe',
      reporter: 'HQT52N',
    },
  ],
  evidence: [],
  witnesses: [
    {
      code: 'OTHER_PERSON',
      firstName: 'ICLQUENS',
      lastName: 'HANNISTA',
      reporter: 'HQT52N',
    },
  ],
  hearings: [
    {
      id: 294486,
      locationId: 78703,
      dateTimeOfHearing: '2011-02-18T10:00:00',
      oicHearingType: 'GOV_ADULT',
      outcome: {
        id: 284319,
        adjudicator: 'IQS13Z',
        code: 'COMPLETE',
        details: '',
        plea: 'ABSTAIN',
      },
      agencyId: 'GHI',
    },
  ],
  disIssueHistory: [],
  outcomes: [
    {
      hearing: {
        id: 294486,
        locationId: 78703,
        dateTimeOfHearing: '2011-02-18T10:00:00',
        oicHearingType: 'GOV_ADULT',
        outcome: {
          id: 284319,
          adjudicator: 'IQS13Z',
          code: 'COMPLETE',
          details: '',
          plea: 'ABSTAIN',
        },
        agencyId: 'GHI',
      },
      outcome: {
        outcome: {
          id: 248206,
          code: 'NOT_PROCEED',
          reason: 'RELEASED',
          canRemove: true,
        },
      },
    },
  ],
  punishments: [],
  punishmentComments: [],
  outcomeEnteredInNomis: false,
  overrideAgencyId: 'BWI',
  originatingAgencyId: 'GHI',
  transferableActionsAllowed: true,
  linkedChargeNumbers: [],
  canActionFromHistory: false,
}
