export const enum AUDIT_ACTIONS {
  VIEW_PAGE = 'VIEW_PAGE',
  VIEW_EXTERNAL_PAGE = 'VIEW_EXTERNAL_PAGE',
}

export const enum AUDIT_PAGE_NAMES {
  HOMEPAGE = 'HOMEPAGE',
  ADJUDICATIONS = 'ADJUDICATIONS',
  CHARGE = 'CHARGE',
  PROFILE = 'PROFILE',
  REMOVE_ACCESS = 'REMOVE_ACCESS',
  SETTINGS = 'SETTINGS',
  TIMETABLE = 'TIMETABLE',
  TRANSACTIONS = 'TRANSACTIONS',
  VISITS = 'VISITS',
  EXTERNAL = 'EXTERNAL',
}
