// eslint-disable-next-line import/prefer-default-export
export const prisonAgencyIds = {
  Berwyn: 'BWI',
  Bullingdon: 'BNI',
  Cardiff: 'CFI',
  CookhamWood: 'CKI',
  Chelmsford: 'CDI',
  Erlestoke: 'EEI',
  FelthamA: 'FYI',
  FelthamB: 'FMI',
  Garth: 'GHI',
  Lindholme: 'LHI',
  NewHall: 'NHI',
  Ranby: 'RNI',
  StokeHeath: 'SHI',
  Styal: 'STI',
  Swaleside: 'SLI',
  TheMount: 'MTI',
  Wayland: 'WLI',
  Werrington: 'WNI',
  Wetherby: 'WYI',
  Woodhill: 'WHI',
}
